package reactor

import (
	"fmt"
	"strings"
)

// NFSClient represents NFS client configuration
type NFSClient struct {
	Address string
	Options string
}

// ISCSILun represents iSCSI LUN configuration
type ISCSILun struct {
	LUN          int
	BSType       string
	VolumeNumber int
}

// NVMeNamespace represents NVMe namespace configuration
type NVMeNamespace struct {
	NSID         int
	VolumeNumber int
}

// GenerateNFSPromoterConfig generates drbd-reactor promoter TOML config for NFS gateway
func GenerateNFSPromoterConfig(resourceName, serviceIP, exportPath string, clients []NFSClient, options string, nodes []string) string {
	drbdDevice := fmt.Sprintf("/dev/drbd/by-res/%s/0", resourceName)
	nfsInfodir := fmt.Sprintf("/srv/ha/internal/%s", resourceName)

	// Build OCF resource commands
	var resources []string

	// 1. Filesystem agent - mount DRBD device
	fsOCF := fmt.Sprintf(`  ocf:heartbeat:Filesystem fs_%s
    device = "%s"
    directory = "%s"
    fstype = "ext4"
    run_fsck = "no"`, resourceName, drbdDevice, exportPath)
	resources = append(resources, fsOCF)

	// 2. nfsserver agent - manage NFS server service
	nfsOCF := fmt.Sprintf(`  ocf:heartbeat:nfsserver nfsserver_%s
    nfs_ip = "%s"
    nfs_server_scope = "%s"
    nfs_shared_infodir = "%s"`, resourceName, serviceIP, serviceIP, nfsInfodir)
	resources = append(resources, nfsOCF)

	// 3. exportfs agent - manage NFS exports
	clientsStr := formatNFSClients(clients)
	exportOCF := fmt.Sprintf(`  ocf:heartbeat:exportfs export_1_0_%s
    directory = "%s"
    clientspec = "%s"
    options = "%s"`, resourceName, exportPath, clientsStr, options)
	resources = append(resources, exportOCF)

	// 4. IPaddr2 agent - manage virtual IP (must be last)
	vipOCF := fmt.Sprintf(`  ocf:heartbeat:IPaddr2 service_ip_%s
    ip = "%s"
    cidr_netmask = 24`, resourceName, serviceIP)
	resources = append(resources, vipOCF)

	// Generate TOML config
	toml := fmt.Sprintf(`# drbd-reactor promoter configuration for NFS gateway: %s
# Generated by sds-controller

[[promoter.resources.%s]]
  runner = "systemd"
  start = [
%s
  ]
  on-drbd-demote-failure = "stop-on-error"
  secondary-force = true
  preferred-nodes = [%s]

`, resourceName, resourceName, strings.Join(resources, ",\n"), strings.Join(nodes, ", "))

	return toml
}

// GenerateiSCSIPromoterConfig generates drbd-reactor promoter TOML config for iSCSI gateway
func GenerateiSCSIPromoterConfig(resourceName, serviceIP, iqn string, tpgt int, luns []ISCSILun, implementation string, nodes []string) string {
	var resources []string

	// 1. IPaddr2 agent - manage virtual IP
	vipOCF := fmt.Sprintf(`  ocf:heartbeat:IPaddr2 p_%s_vip
    ip = "%s"
    cidr_netmask = 24`, resourceName, serviceIP)
	resources = append(resources, vipOCF)

	// 2. iSCSITarget agent - manage iSCSI target
	portal := fmt.Sprintf("\"%s:3260\"", serviceIP)
	targetOCF := fmt.Sprintf(`  ocf:heartbeat:HA-SDS-iSCSITarget p_%s_target
    implementation = "%s"
    iqn = "%s"
    portals = [%s]`, resourceName, implementation, iqn, portal)
	resources = append(resources, targetOCF)

	// 3. iSCSILogicalUnit agents - manage LUNs
	for _, lun := range luns {
		drbdDevice := fmt.Sprintf("/dev/drbd/by-res/%s/%d", resourceName, lun.VolumeNumber)
		lunInstance := fmt.Sprintf("%s_%d", resourceName, lun.LUN)

		lunOCF := fmt.Sprintf(`  ocf:heartbeat:HA-SDS-iSCSILogicalUnit %s
    implementation = "%s"
    target_iqn = "%s"
    liot_bstype = "%s"
    path = "%s"
    lun = %d`, lunInstance, implementation, iqn, lun.BSType, drbdDevice, lun.LUN)
		resources = append(resources, lunOCF)
	}

	// Generate TOML config
	toml := fmt.Sprintf(`# drbd-reactor promoter configuration for iSCSI gateway: %s
# Generated by sds-controller

[[promoter.resources.%s]]
  runner = "systemd"
  start = [
%s
  ]
  on-drbd-demote-failure = "stop-on-error"
  secondary-force = true
  preferred-nodes = [%s]

`, resourceName, resourceName, strings.Join(resources, ",\n"), strings.Join(nodes, ", "))

	return toml
}

// GenerateNVMePromoterConfig generates drbd-reactor promoter TOML config for NVMe gateway
func GenerateNVMePromoterConfig(resourceName, serviceIP, nqn string, namespaces []NVMeNamespace, nodes []string) string {
	// For now, basic NVMe configuration
	// TODO: Add NVMe-oF specific OCF agents when available

	// Generate TOML config
	toml := fmt.Sprintf(`# drbd-reactor promoter configuration for NVMe gateway: %s
# Generated by sds-controller

[[promoter.resources.%s]]
  runner = "systemd"
  start = []
  on-drbd-demote-failure = "stop-on-error"
  secondary-force = true
  preferred-nodes = [%s]

`, resourceName, resourceName, strings.Join(nodes, ", "))

	return toml
}

// formatNFSClients formats NFS clients for exportfs
func formatNFSClients(clients []NFSClient) string {
	var parts []string
	for _, client := range clients {
		parts = append(parts, fmt.Sprintf("%s(%s)", client.Address, client.Options))
	}
	return strings.Join(parts, " ")
}

// StartAction represents a single start action in promoter config
type StartAction struct {
	Type string // "systemd", "ocf", etc.
	Name string // Action name
	Args map[string]string
}

// GenerateGenericPromoterConfig generates a generic drbd-reactor promoter TOML config
// This is used for simple HA setups with systemd services and OCF resources
func GenerateGenericPromoterConfig(resourceName string, units []string, ocfResources []map[string]string) string {
	var startActions []string

	// Add systemd units
	for _, unit := range units {
		startActions = append(startActions, fmt.Sprintf(`  "%s"`, unit))
	}

	// Add OCF resources
	for _, ocf := range ocfResources {
		// Extract OCF parameters
		provider, ok := ocf["provider"]
		if !ok {
			provider = "heartbeat"
		}
		agent, ok := ocf["agent"]
		if !ok {
			continue
		}
		actionName, ok := ocf["name"]
		if !ok {
			actionName = agent
		}

		// Build OCF action string
		var parts []string
		for k, v := range ocf {
			if k != "provider" && k != "agent" && k != "name" {
				parts = append(parts, fmt.Sprintf("%s=%s", k, v))
			}
		}

		var ocfStr string
		if len(parts) > 0 {
			ocfStr = fmt.Sprintf(`  "ocf:%s:%s %s %s"`, provider, agent, actionName, strings.Join(parts, " "))
		} else {
			ocfStr = fmt.Sprintf(`  "ocf:%s:%s %s"`, provider, agent, actionName)
		}
		startActions = append(startActions, ocfStr)
	}

	// Generate TOML config snippet for drbd-reactor promoter
	// Format: [[promoter]] followed by [promoter.resources.<id>]
	toml := fmt.Sprintf(`[[promoter]]
[promoter.resources.%s]
runner = "systemd"
start = [
%s
]
on-drbd-demote-failure = "reboot"

`, resourceName, strings.Join(startActions, ",\n"))

	return toml
}
