apiVersion: v1
kind: ServiceAccount
metadata: { name: sds-csi-controller, namespace: kube-system }
---
apiVersion: v1
kind: ServiceAccount
metadata: { name: sds-csi-node, namespace: kube-system }
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata: { name: sds-csi-provisioner }
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses", "csinodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata: { name: sds-csi-provisioner }
subjects:
  - kind: ServiceAccount
    name: sds-csi-controller
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: sds-csi-provisioner
  apiGroup: rbac.authorization.k8s.io
