// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: api/proto/v1/sds.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SDSController_CreatePool_FullMethodName         = "/v1.SDSController/CreatePool"
	SDSController_DeletePool_FullMethodName         = "/v1.SDSController/DeletePool"
	SDSController_GetPool_FullMethodName            = "/v1.SDSController/GetPool"
	SDSController_ListPools_FullMethodName          = "/v1.SDSController/ListPools"
	SDSController_AddDiskToPool_FullMethodName      = "/v1.SDSController/AddDiskToPool"
	SDSController_RegisterNode_FullMethodName       = "/v1.SDSController/RegisterNode"
	SDSController_UnregisterNode_FullMethodName     = "/v1.SDSController/UnregisterNode"
	SDSController_GetNode_FullMethodName            = "/v1.SDSController/GetNode"
	SDSController_ListNodes_FullMethodName          = "/v1.SDSController/ListNodes"
	SDSController_CreateResource_FullMethodName     = "/v1.SDSController/CreateResource"
	SDSController_DeleteResource_FullMethodName     = "/v1.SDSController/DeleteResource"
	SDSController_GetResource_FullMethodName        = "/v1.SDSController/GetResource"
	SDSController_ListResources_FullMethodName      = "/v1.SDSController/ListResources"
	SDSController_AddVolume_FullMethodName          = "/v1.SDSController/AddVolume"
	SDSController_RemoveVolume_FullMethodName       = "/v1.SDSController/RemoveVolume"
	SDSController_ResizeVolume_FullMethodName       = "/v1.SDSController/ResizeVolume"
	SDSController_ResourceStatus_FullMethodName     = "/v1.SDSController/ResourceStatus"
	SDSController_SetPrimary_FullMethodName         = "/v1.SDSController/SetPrimary"
	SDSController_SetSecondary_FullMethodName       = "/v1.SDSController/SetSecondary"
	SDSController_CreateFilesystem_FullMethodName   = "/v1.SDSController/CreateFilesystem"
	SDSController_MountResource_FullMethodName      = "/v1.SDSController/MountResource"
	SDSController_UnmountResource_FullMethodName    = "/v1.SDSController/UnmountResource"
	SDSController_MakeHa_FullMethodName             = "/v1.SDSController/MakeHa"
	SDSController_EvictHa_FullMethodName            = "/v1.SDSController/EvictHa"
	SDSController_DeleteHa_FullMethodName           = "/v1.SDSController/DeleteHa"
	SDSController_GetHa_FullMethodName              = "/v1.SDSController/GetHa"
	SDSController_ListHa_FullMethodName             = "/v1.SDSController/ListHa"
	SDSController_CreateSnapshot_FullMethodName     = "/v1.SDSController/CreateSnapshot"
	SDSController_DeleteSnapshot_FullMethodName     = "/v1.SDSController/DeleteSnapshot"
	SDSController_RestoreSnapshot_FullMethodName    = "/v1.SDSController/RestoreSnapshot"
	SDSController_ListSnapshots_FullMethodName      = "/v1.SDSController/ListSnapshots"
	SDSController_CreateNFSGateway_FullMethodName   = "/v1.SDSController/CreateNFSGateway"
	SDSController_CreateISCSIGateway_FullMethodName = "/v1.SDSController/CreateISCSIGateway"
	SDSController_CreateNVMeGateway_FullMethodName  = "/v1.SDSController/CreateNVMeGateway"
	SDSController_DeleteGateway_FullMethodName      = "/v1.SDSController/DeleteGateway"
	SDSController_GetGateway_FullMethodName         = "/v1.SDSController/GetGateway"
	SDSController_ListGateways_FullMethodName       = "/v1.SDSController/ListGateways"
	SDSController_StartGateway_FullMethodName       = "/v1.SDSController/StartGateway"
	SDSController_StopGateway_FullMethodName        = "/v1.SDSController/StopGateway"
	SDSController_CreateZFSPool_FullMethodName      = "/v1.SDSController/CreateZFSPool"
	SDSController_DeleteZFSPool_FullMethodName      = "/v1.SDSController/DeleteZFSPool"
	SDSController_ListZFSpools_FullMethodName       = "/v1.SDSController/ListZFSpools"
	SDSController_CreateZFSDataset_FullMethodName   = "/v1.SDSController/CreateZFSDataset"
	SDSController_CreateZFSVolume_FullMethodName    = "/v1.SDSController/CreateZFSVolume"
	SDSController_ResizeZFSVolume_FullMethodName    = "/v1.SDSController/ResizeZFSVolume"
	SDSController_DeleteZFSDataset_FullMethodName   = "/v1.SDSController/DeleteZFSDataset"
	SDSController_CreateZFSSnapshot_FullMethodName  = "/v1.SDSController/CreateZFSSnapshot"
	SDSController_DeleteZFSSnapshot_FullMethodName  = "/v1.SDSController/DeleteZFSSnapshot"
	SDSController_ListZFSSnapshots_FullMethodName   = "/v1.SDSController/ListZFSSnapshots"
	SDSController_RestoreZFSSnapshot_FullMethodName = "/v1.SDSController/RestoreZFSSnapshot"
	SDSController_CloneZFSSnapshot_FullMethodName   = "/v1.SDSController/CloneZFSSnapshot"
	SDSController_CreateLvmSnapshot_FullMethodName  = "/v1.SDSController/CreateLvmSnapshot"
	SDSController_DeleteLvmSnapshot_FullMethodName  = "/v1.SDSController/DeleteLvmSnapshot"
	SDSController_ListLvmSnapshots_FullMethodName   = "/v1.SDSController/ListLvmSnapshots"
	SDSController_RestoreLvmSnapshot_FullMethodName = "/v1.SDSController/RestoreLvmSnapshot"
)

// SDSControllerClient is the client API for SDSController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SDS Controller Service
type SDSControllerClient interface {
	// Pool operations
	CreatePool(ctx context.Context, in *CreatePoolRequest, opts ...grpc.CallOption) (*CreatePoolResponse, error)
	DeletePool(ctx context.Context, in *DeletePoolRequest, opts ...grpc.CallOption) (*DeletePoolResponse, error)
	GetPool(ctx context.Context, in *GetPoolRequest, opts ...grpc.CallOption) (*GetPoolResponse, error)
	ListPools(ctx context.Context, in *ListPoolsRequest, opts ...grpc.CallOption) (*ListPoolsResponse, error)
	AddDiskToPool(ctx context.Context, in *AddDiskToPoolRequest, opts ...grpc.CallOption) (*AddDiskToPoolResponse, error)
	// Node operations
	RegisterNode(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*RegisterNodeResponse, error)
	UnregisterNode(ctx context.Context, in *UnregisterNodeRequest, opts ...grpc.CallOption) (*UnregisterNodeResponse, error)
	GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeResponse, error)
	ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error)
	// Resource operations
	CreateResource(ctx context.Context, in *CreateResourceRequest, opts ...grpc.CallOption) (*CreateResourceResponse, error)
	DeleteResource(ctx context.Context, in *DeleteResourceRequest, opts ...grpc.CallOption) (*DeleteResourceResponse, error)
	GetResource(ctx context.Context, in *GetResourceRequest, opts ...grpc.CallOption) (*GetResourceResponse, error)
	ListResources(ctx context.Context, in *ListResourcesRequest, opts ...grpc.CallOption) (*ListResourcesResponse, error)
	AddVolume(ctx context.Context, in *AddVolumeRequest, opts ...grpc.CallOption) (*AddVolumeResponse, error)
	RemoveVolume(ctx context.Context, in *RemoveVolumeRequest, opts ...grpc.CallOption) (*RemoveVolumeResponse, error)
	ResizeVolume(ctx context.Context, in *ResizeVolumeRequest, opts ...grpc.CallOption) (*ResizeVolumeResponse, error)
	ResourceStatus(ctx context.Context, in *ResourceStatusRequest, opts ...grpc.CallOption) (*ResourceStatusResponse, error)
	SetPrimary(ctx context.Context, in *SetPrimaryRequest, opts ...grpc.CallOption) (*SetPrimaryResponse, error)
	SetSecondary(ctx context.Context, in *SetSecondaryRequest, opts ...grpc.CallOption) (*SetSecondaryResponse, error)
	CreateFilesystem(ctx context.Context, in *CreateFilesystemRequest, opts ...grpc.CallOption) (*CreateFilesystemResponse, error)
	MountResource(ctx context.Context, in *MountResourceRequest, opts ...grpc.CallOption) (*MountResourceResponse, error)
	UnmountResource(ctx context.Context, in *UnmountResourceRequest, opts ...grpc.CallOption) (*UnmountResourceResponse, error)
	MakeHa(ctx context.Context, in *MakeHaRequest, opts ...grpc.CallOption) (*MakeHaResponse, error)
	EvictHa(ctx context.Context, in *EvictHaRequest, opts ...grpc.CallOption) (*EvictHaResponse, error)
	DeleteHa(ctx context.Context, in *DeleteHaRequest, opts ...grpc.CallOption) (*DeleteHaResponse, error)
	GetHa(ctx context.Context, in *GetHaRequest, opts ...grpc.CallOption) (*GetHaResponse, error)
	ListHa(ctx context.Context, in *ListHaRequest, opts ...grpc.CallOption) (*ListHaResponse, error)
	// Snapshot operations
	CreateSnapshot(ctx context.Context, in *CreateSnapshotRequest, opts ...grpc.CallOption) (*CreateSnapshotResponse, error)
	DeleteSnapshot(ctx context.Context, in *DeleteSnapshotRequest, opts ...grpc.CallOption) (*DeleteSnapshotResponse, error)
	RestoreSnapshot(ctx context.Context, in *RestoreSnapshotRequest, opts ...grpc.CallOption) (*RestoreSnapshotResponse, error)
	ListSnapshots(ctx context.Context, in *ListSnapshotsRequest, opts ...grpc.CallOption) (*ListSnapshotsResponse, error)
	// Gateway operations
	CreateNFSGateway(ctx context.Context, in *CreateNFSGatewayRequest, opts ...grpc.CallOption) (*CreateNFSGatewayResponse, error)
	CreateISCSIGateway(ctx context.Context, in *CreateISCSIGatewayRequest, opts ...grpc.CallOption) (*CreateISCSIGatewayResponse, error)
	CreateNVMeGateway(ctx context.Context, in *CreateNVMeGatewayRequest, opts ...grpc.CallOption) (*CreateNVMeGatewayResponse, error)
	DeleteGateway(ctx context.Context, in *DeleteGatewayRequest, opts ...grpc.CallOption) (*DeleteGatewayResponse, error)
	GetGateway(ctx context.Context, in *GetGatewayRequest, opts ...grpc.CallOption) (*GetGatewayResponse, error)
	ListGateways(ctx context.Context, in *ListGatewaysRequest, opts ...grpc.CallOption) (*ListGatewaysResponse, error)
	StartGateway(ctx context.Context, in *StartGatewayRequest, opts ...grpc.CallOption) (*StartGatewayResponse, error)
	StopGateway(ctx context.Context, in *StopGatewayRequest, opts ...grpc.CallOption) (*StopGatewayResponse, error)
	// ZFS operations
	CreateZFSPool(ctx context.Context, in *CreateZFSPoolRequest, opts ...grpc.CallOption) (*CreateZFSPoolResponse, error)
	DeleteZFSPool(ctx context.Context, in *DeleteZFSPoolRequest, opts ...grpc.CallOption) (*DeleteZFSPoolResponse, error)
	ListZFSpools(ctx context.Context, in *ListZFSPoolsRequest, opts ...grpc.CallOption) (*ListZFSPoolsResponse, error)
	CreateZFSDataset(ctx context.Context, in *CreateZFSDatasetRequest, opts ...grpc.CallOption) (*CreateZFSDatasetResponse, error)
	CreateZFSVolume(ctx context.Context, in *CreateZFSVolumeRequest, opts ...grpc.CallOption) (*CreateZFSVolumeResponse, error)
	ResizeZFSVolume(ctx context.Context, in *ResizeZFSVolumeRequest, opts ...grpc.CallOption) (*ResizeZFSVolumeResponse, error)
	DeleteZFSDataset(ctx context.Context, in *DeleteZFSDatasetRequest, opts ...grpc.CallOption) (*DeleteZFSDatasetResponse, error)
	// ZFS Snapshot operations
	CreateZFSSnapshot(ctx context.Context, in *CreateZFSSnapshotRequest, opts ...grpc.CallOption) (*CreateZFSSnapshotResponse, error)
	DeleteZFSSnapshot(ctx context.Context, in *DeleteZFSSnapshotRequest, opts ...grpc.CallOption) (*DeleteZFSSnapshotResponse, error)
	ListZFSSnapshots(ctx context.Context, in *ListZFSSnapshotsRequest, opts ...grpc.CallOption) (*ListZFSSnapshotsResponse, error)
	RestoreZFSSnapshot(ctx context.Context, in *RestoreZFSSnapshotRequest, opts ...grpc.CallOption) (*RestoreZFSSnapshotResponse, error)
	CloneZFSSnapshot(ctx context.Context, in *CloneZFSSnapshotRequest, opts ...grpc.CallOption) (*CloneZFSSnapshotResponse, error)
	// LVM Snapshot operations
	CreateLvmSnapshot(ctx context.Context, in *CreateLvmSnapshotRequest, opts ...grpc.CallOption) (*CreateLvmSnapshotResponse, error)
	DeleteLvmSnapshot(ctx context.Context, in *DeleteLvmSnapshotRequest, opts ...grpc.CallOption) (*DeleteLvmSnapshotResponse, error)
	ListLvmSnapshots(ctx context.Context, in *ListLvmSnapshotsRequest, opts ...grpc.CallOption) (*ListLvmSnapshotsResponse, error)
	RestoreLvmSnapshot(ctx context.Context, in *RestoreLvmSnapshotRequest, opts ...grpc.CallOption) (*RestoreLvmSnapshotResponse, error)
}

type sDSControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewSDSControllerClient(cc grpc.ClientConnInterface) SDSControllerClient {
	return &sDSControllerClient{cc}
}

func (c *sDSControllerClient) CreatePool(ctx context.Context, in *CreatePoolRequest, opts ...grpc.CallOption) (*CreatePoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePoolResponse)
	err := c.cc.Invoke(ctx, SDSController_CreatePool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDSControllerClient) DeletePool(ctx context.Context, in *DeletePoolRequest, opts ...grpc.CallOption) (*DeletePoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePoolResponse)
	err := c.cc.Invoke(ctx, SDSController_DeletePool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDSControllerClient) GetPool(ctx context.Context, in *GetPoolRequest, opts ...grpc.CallOption) (*GetPoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPoolResponse)
	err := c.cc.Invoke(ctx, SDSController_GetPool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDSControllerClient) ListPools(ctx context.Context, in *ListPoolsRequest, opts ...grpc.CallOption) (*ListPoolsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPoolsResponse)
	err := c.cc.Invoke(ctx, SDSController_ListPools_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDSControllerClient) AddDiskToPool(ctx context.Context, in *AddDiskToPoolRequest, opts ...grpc.CallOption) (*AddDiskToPoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddDiskToPoolResponse)
	err := c.cc.Invoke(ctx, SDSController_AddDiskToPool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDSControllerClient) RegisterNode(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*RegisterNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterNodeResponse)
	err := c.cc.Invoke(ctx, SDSController_RegisterNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDSControllerClient) UnregisterNode(ctx context.Context, in *UnregisterNodeRequest, opts ...grpc.CallOption) (*UnregisterNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnregisterNodeResponse)
	err := c.cc.Invoke(ctx, SDSController_UnregisterNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDSControllerClient) GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodeResponse)
	err := c.cc.Invoke(ctx, SDSController_GetNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDSControllerClient) ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNodesResponse)
	err := c.cc.Invoke(ctx, SDSController_ListNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDSControllerClient) CreateResource(ctx context.Context, in *CreateResourceRequest, opts ...grpc.CallOption) (*CreateResourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateResourceResponse)
	err := c.cc.Invoke(ctx, SDSController_CreateResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDSControllerClient) DeleteResource(ctx context.Context, in *DeleteResourceRequest, opts ...grpc.CallOption) (*DeleteResourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResourceResponse)
	err := c.cc.Invoke(ctx, SDSController_DeleteResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDSControllerClient) GetResource(ctx context.Context, in *GetResourceRequest, opts ...grpc.CallOption) (*GetResourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResourceResponse)
	err := c.cc.Invoke(ctx, SDSController_GetResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDSControllerClient) ListResources(ctx context.Context, in *ListResourcesRequest, opts ...grpc.CallOption) (*ListResourcesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResourcesResponse)
	err := c.cc.Invoke(ctx, SDSController_ListResources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDSControllerClient) AddVolume(ctx context.Context, in *AddVolumeRequest, opts ...grpc.CallOption) (*AddVolumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddVolumeResponse)
	err := c.cc.Invoke(ctx, SDSController_AddVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDSControllerClient) RemoveVolume(ctx context.Context, in *RemoveVolumeRequest, opts ...grpc.CallOption) (*RemoveVolumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveVolumeResponse)
	err := c.cc.Invoke(ctx, SDSController_RemoveVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDSControllerClient) ResizeVolume(ctx context.Context, in *ResizeVolumeRequest, opts ...grpc.CallOption) (*ResizeVolumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResizeVolumeResponse)
	err := c.cc.Invoke(ctx, SDSController_ResizeVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDSControllerClient) ResourceStatus(ctx context.Context, in *ResourceStatusRequest, opts ...grpc.CallOption) (*ResourceStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResourceStatusResponse)
	err := c.cc.Invoke(ctx, SDSController_ResourceStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDSControllerClient) SetPrimary(ctx context.Context, in *SetPrimaryRequest, opts ...grpc.CallOption) (*SetPrimaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetPrimaryResponse)
	err := c.cc.Invoke(ctx, SDSController_SetPrimary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDSControllerClient) SetSecondary(ctx context.Context, in *SetSecondaryRequest, opts ...grpc.CallOption) (*SetSecondaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetSecondaryResponse)
	err := c.cc.Invoke(ctx, SDSController_SetSecondary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDSControllerClient) CreateFilesystem(ctx context.Context, in *CreateFilesystemRequest, opts ...grpc.CallOption) (*CreateFilesystemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateFilesystemResponse)
	err := c.cc.Invoke(ctx, SDSController_CreateFilesystem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDSControllerClient) MountResource(ctx context.Context, in *MountResourceRequest, opts ...grpc.CallOption) (*MountResourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MountResourceResponse)
	err := c.cc.Invoke(ctx, SDSController_MountResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDSControllerClient) UnmountResource(ctx context.Context, in *UnmountResourceRequest, opts ...grpc.CallOption) (*UnmountResourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnmountResourceResponse)
	err := c.cc.Invoke(ctx, SDSController_UnmountResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDSControllerClient) MakeHa(ctx context.Context, in *MakeHaRequest, opts ...grpc.CallOption) (*MakeHaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MakeHaResponse)
	err := c.cc.Invoke(ctx, SDSController_MakeHa_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDSControllerClient) EvictHa(ctx context.Context, in *EvictHaRequest, opts ...grpc.CallOption) (*EvictHaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvictHaResponse)
	err := c.cc.Invoke(ctx, SDSController_EvictHa_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDSControllerClient) DeleteHa(ctx context.Context, in *DeleteHaRequest, opts ...grpc.CallOption) (*DeleteHaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteHaResponse)
	err := c.cc.Invoke(ctx, SDSController_DeleteHa_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDSControllerClient) GetHa(ctx context.Context, in *GetHaRequest, opts ...grpc.CallOption) (*GetHaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHaResponse)
	err := c.cc.Invoke(ctx, SDSController_GetHa_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDSControllerClient) ListHa(ctx context.Context, in *ListHaRequest, opts ...grpc.CallOption) (*ListHaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListHaResponse)
	err := c.cc.Invoke(ctx, SDSController_ListHa_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDSControllerClient) CreateSnapshot(ctx context.Context, in *CreateSnapshotRequest, opts ...grpc.CallOption) (*CreateSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSnapshotResponse)
	err := c.cc.Invoke(ctx, SDSController_CreateSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDSControllerClient) DeleteSnapshot(ctx context.Context, in *DeleteSnapshotRequest, opts ...grpc.CallOption) (*DeleteSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSnapshotResponse)
	err := c.cc.Invoke(ctx, SDSController_DeleteSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDSControllerClient) RestoreSnapshot(ctx context.Context, in *RestoreSnapshotRequest, opts ...grpc.CallOption) (*RestoreSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestoreSnapshotResponse)
	err := c.cc.Invoke(ctx, SDSController_RestoreSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDSControllerClient) ListSnapshots(ctx context.Context, in *ListSnapshotsRequest, opts ...grpc.CallOption) (*ListSnapshotsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSnapshotsResponse)
	err := c.cc.Invoke(ctx, SDSController_ListSnapshots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDSControllerClient) CreateNFSGateway(ctx context.Context, in *CreateNFSGatewayRequest, opts ...grpc.CallOption) (*CreateNFSGatewayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateNFSGatewayResponse)
	err := c.cc.Invoke(ctx, SDSController_CreateNFSGateway_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDSControllerClient) CreateISCSIGateway(ctx context.Context, in *CreateISCSIGatewayRequest, opts ...grpc.CallOption) (*CreateISCSIGatewayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateISCSIGatewayResponse)
	err := c.cc.Invoke(ctx, SDSController_CreateISCSIGateway_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDSControllerClient) CreateNVMeGateway(ctx context.Context, in *CreateNVMeGatewayRequest, opts ...grpc.CallOption) (*CreateNVMeGatewayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateNVMeGatewayResponse)
	err := c.cc.Invoke(ctx, SDSController_CreateNVMeGateway_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDSControllerClient) DeleteGateway(ctx context.Context, in *DeleteGatewayRequest, opts ...grpc.CallOption) (*DeleteGatewayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteGatewayResponse)
	err := c.cc.Invoke(ctx, SDSController_DeleteGateway_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDSControllerClient) GetGateway(ctx context.Context, in *GetGatewayRequest, opts ...grpc.CallOption) (*GetGatewayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGatewayResponse)
	err := c.cc.Invoke(ctx, SDSController_GetGateway_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDSControllerClient) ListGateways(ctx context.Context, in *ListGatewaysRequest, opts ...grpc.CallOption) (*ListGatewaysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGatewaysResponse)
	err := c.cc.Invoke(ctx, SDSController_ListGateways_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDSControllerClient) StartGateway(ctx context.Context, in *StartGatewayRequest, opts ...grpc.CallOption) (*StartGatewayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartGatewayResponse)
	err := c.cc.Invoke(ctx, SDSController_StartGateway_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDSControllerClient) StopGateway(ctx context.Context, in *StopGatewayRequest, opts ...grpc.CallOption) (*StopGatewayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopGatewayResponse)
	err := c.cc.Invoke(ctx, SDSController_StopGateway_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDSControllerClient) CreateZFSPool(ctx context.Context, in *CreateZFSPoolRequest, opts ...grpc.CallOption) (*CreateZFSPoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateZFSPoolResponse)
	err := c.cc.Invoke(ctx, SDSController_CreateZFSPool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDSControllerClient) DeleteZFSPool(ctx context.Context, in *DeleteZFSPoolRequest, opts ...grpc.CallOption) (*DeleteZFSPoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteZFSPoolResponse)
	err := c.cc.Invoke(ctx, SDSController_DeleteZFSPool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDSControllerClient) ListZFSpools(ctx context.Context, in *ListZFSPoolsRequest, opts ...grpc.CallOption) (*ListZFSPoolsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListZFSPoolsResponse)
	err := c.cc.Invoke(ctx, SDSController_ListZFSpools_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDSControllerClient) CreateZFSDataset(ctx context.Context, in *CreateZFSDatasetRequest, opts ...grpc.CallOption) (*CreateZFSDatasetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateZFSDatasetResponse)
	err := c.cc.Invoke(ctx, SDSController_CreateZFSDataset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDSControllerClient) CreateZFSVolume(ctx context.Context, in *CreateZFSVolumeRequest, opts ...grpc.CallOption) (*CreateZFSVolumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateZFSVolumeResponse)
	err := c.cc.Invoke(ctx, SDSController_CreateZFSVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDSControllerClient) ResizeZFSVolume(ctx context.Context, in *ResizeZFSVolumeRequest, opts ...grpc.CallOption) (*ResizeZFSVolumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResizeZFSVolumeResponse)
	err := c.cc.Invoke(ctx, SDSController_ResizeZFSVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDSControllerClient) DeleteZFSDataset(ctx context.Context, in *DeleteZFSDatasetRequest, opts ...grpc.CallOption) (*DeleteZFSDatasetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteZFSDatasetResponse)
	err := c.cc.Invoke(ctx, SDSController_DeleteZFSDataset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDSControllerClient) CreateZFSSnapshot(ctx context.Context, in *CreateZFSSnapshotRequest, opts ...grpc.CallOption) (*CreateZFSSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateZFSSnapshotResponse)
	err := c.cc.Invoke(ctx, SDSController_CreateZFSSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDSControllerClient) DeleteZFSSnapshot(ctx context.Context, in *DeleteZFSSnapshotRequest, opts ...grpc.CallOption) (*DeleteZFSSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteZFSSnapshotResponse)
	err := c.cc.Invoke(ctx, SDSController_DeleteZFSSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDSControllerClient) ListZFSSnapshots(ctx context.Context, in *ListZFSSnapshotsRequest, opts ...grpc.CallOption) (*ListZFSSnapshotsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListZFSSnapshotsResponse)
	err := c.cc.Invoke(ctx, SDSController_ListZFSSnapshots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDSControllerClient) RestoreZFSSnapshot(ctx context.Context, in *RestoreZFSSnapshotRequest, opts ...grpc.CallOption) (*RestoreZFSSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestoreZFSSnapshotResponse)
	err := c.cc.Invoke(ctx, SDSController_RestoreZFSSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDSControllerClient) CloneZFSSnapshot(ctx context.Context, in *CloneZFSSnapshotRequest, opts ...grpc.CallOption) (*CloneZFSSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloneZFSSnapshotResponse)
	err := c.cc.Invoke(ctx, SDSController_CloneZFSSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDSControllerClient) CreateLvmSnapshot(ctx context.Context, in *CreateLvmSnapshotRequest, opts ...grpc.CallOption) (*CreateLvmSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateLvmSnapshotResponse)
	err := c.cc.Invoke(ctx, SDSController_CreateLvmSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDSControllerClient) DeleteLvmSnapshot(ctx context.Context, in *DeleteLvmSnapshotRequest, opts ...grpc.CallOption) (*DeleteLvmSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteLvmSnapshotResponse)
	err := c.cc.Invoke(ctx, SDSController_DeleteLvmSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDSControllerClient) ListLvmSnapshots(ctx context.Context, in *ListLvmSnapshotsRequest, opts ...grpc.CallOption) (*ListLvmSnapshotsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLvmSnapshotsResponse)
	err := c.cc.Invoke(ctx, SDSController_ListLvmSnapshots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sDSControllerClient) RestoreLvmSnapshot(ctx context.Context, in *RestoreLvmSnapshotRequest, opts ...grpc.CallOption) (*RestoreLvmSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestoreLvmSnapshotResponse)
	err := c.cc.Invoke(ctx, SDSController_RestoreLvmSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SDSControllerServer is the server API for SDSController service.
// All implementations must embed UnimplementedSDSControllerServer
// for forward compatibility.
//
// SDS Controller Service
type SDSControllerServer interface {
	// Pool operations
	CreatePool(context.Context, *CreatePoolRequest) (*CreatePoolResponse, error)
	DeletePool(context.Context, *DeletePoolRequest) (*DeletePoolResponse, error)
	GetPool(context.Context, *GetPoolRequest) (*GetPoolResponse, error)
	ListPools(context.Context, *ListPoolsRequest) (*ListPoolsResponse, error)
	AddDiskToPool(context.Context, *AddDiskToPoolRequest) (*AddDiskToPoolResponse, error)
	// Node operations
	RegisterNode(context.Context, *RegisterNodeRequest) (*RegisterNodeResponse, error)
	UnregisterNode(context.Context, *UnregisterNodeRequest) (*UnregisterNodeResponse, error)
	GetNode(context.Context, *GetNodeRequest) (*GetNodeResponse, error)
	ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error)
	// Resource operations
	CreateResource(context.Context, *CreateResourceRequest) (*CreateResourceResponse, error)
	DeleteResource(context.Context, *DeleteResourceRequest) (*DeleteResourceResponse, error)
	GetResource(context.Context, *GetResourceRequest) (*GetResourceResponse, error)
	ListResources(context.Context, *ListResourcesRequest) (*ListResourcesResponse, error)
	AddVolume(context.Context, *AddVolumeRequest) (*AddVolumeResponse, error)
	RemoveVolume(context.Context, *RemoveVolumeRequest) (*RemoveVolumeResponse, error)
	ResizeVolume(context.Context, *ResizeVolumeRequest) (*ResizeVolumeResponse, error)
	ResourceStatus(context.Context, *ResourceStatusRequest) (*ResourceStatusResponse, error)
	SetPrimary(context.Context, *SetPrimaryRequest) (*SetPrimaryResponse, error)
	SetSecondary(context.Context, *SetSecondaryRequest) (*SetSecondaryResponse, error)
	CreateFilesystem(context.Context, *CreateFilesystemRequest) (*CreateFilesystemResponse, error)
	MountResource(context.Context, *MountResourceRequest) (*MountResourceResponse, error)
	UnmountResource(context.Context, *UnmountResourceRequest) (*UnmountResourceResponse, error)
	MakeHa(context.Context, *MakeHaRequest) (*MakeHaResponse, error)
	EvictHa(context.Context, *EvictHaRequest) (*EvictHaResponse, error)
	DeleteHa(context.Context, *DeleteHaRequest) (*DeleteHaResponse, error)
	GetHa(context.Context, *GetHaRequest) (*GetHaResponse, error)
	ListHa(context.Context, *ListHaRequest) (*ListHaResponse, error)
	// Snapshot operations
	CreateSnapshot(context.Context, *CreateSnapshotRequest) (*CreateSnapshotResponse, error)
	DeleteSnapshot(context.Context, *DeleteSnapshotRequest) (*DeleteSnapshotResponse, error)
	RestoreSnapshot(context.Context, *RestoreSnapshotRequest) (*RestoreSnapshotResponse, error)
	ListSnapshots(context.Context, *ListSnapshotsRequest) (*ListSnapshotsResponse, error)
	// Gateway operations
	CreateNFSGateway(context.Context, *CreateNFSGatewayRequest) (*CreateNFSGatewayResponse, error)
	CreateISCSIGateway(context.Context, *CreateISCSIGatewayRequest) (*CreateISCSIGatewayResponse, error)
	CreateNVMeGateway(context.Context, *CreateNVMeGatewayRequest) (*CreateNVMeGatewayResponse, error)
	DeleteGateway(context.Context, *DeleteGatewayRequest) (*DeleteGatewayResponse, error)
	GetGateway(context.Context, *GetGatewayRequest) (*GetGatewayResponse, error)
	ListGateways(context.Context, *ListGatewaysRequest) (*ListGatewaysResponse, error)
	StartGateway(context.Context, *StartGatewayRequest) (*StartGatewayResponse, error)
	StopGateway(context.Context, *StopGatewayRequest) (*StopGatewayResponse, error)
	// ZFS operations
	CreateZFSPool(context.Context, *CreateZFSPoolRequest) (*CreateZFSPoolResponse, error)
	DeleteZFSPool(context.Context, *DeleteZFSPoolRequest) (*DeleteZFSPoolResponse, error)
	ListZFSpools(context.Context, *ListZFSPoolsRequest) (*ListZFSPoolsResponse, error)
	CreateZFSDataset(context.Context, *CreateZFSDatasetRequest) (*CreateZFSDatasetResponse, error)
	CreateZFSVolume(context.Context, *CreateZFSVolumeRequest) (*CreateZFSVolumeResponse, error)
	ResizeZFSVolume(context.Context, *ResizeZFSVolumeRequest) (*ResizeZFSVolumeResponse, error)
	DeleteZFSDataset(context.Context, *DeleteZFSDatasetRequest) (*DeleteZFSDatasetResponse, error)
	// ZFS Snapshot operations
	CreateZFSSnapshot(context.Context, *CreateZFSSnapshotRequest) (*CreateZFSSnapshotResponse, error)
	DeleteZFSSnapshot(context.Context, *DeleteZFSSnapshotRequest) (*DeleteZFSSnapshotResponse, error)
	ListZFSSnapshots(context.Context, *ListZFSSnapshotsRequest) (*ListZFSSnapshotsResponse, error)
	RestoreZFSSnapshot(context.Context, *RestoreZFSSnapshotRequest) (*RestoreZFSSnapshotResponse, error)
	CloneZFSSnapshot(context.Context, *CloneZFSSnapshotRequest) (*CloneZFSSnapshotResponse, error)
	// LVM Snapshot operations
	CreateLvmSnapshot(context.Context, *CreateLvmSnapshotRequest) (*CreateLvmSnapshotResponse, error)
	DeleteLvmSnapshot(context.Context, *DeleteLvmSnapshotRequest) (*DeleteLvmSnapshotResponse, error)
	ListLvmSnapshots(context.Context, *ListLvmSnapshotsRequest) (*ListLvmSnapshotsResponse, error)
	RestoreLvmSnapshot(context.Context, *RestoreLvmSnapshotRequest) (*RestoreLvmSnapshotResponse, error)
	mustEmbedUnimplementedSDSControllerServer()
}

// UnimplementedSDSControllerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSDSControllerServer struct{}

func (UnimplementedSDSControllerServer) CreatePool(context.Context, *CreatePoolRequest) (*CreatePoolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePool not implemented")
}
func (UnimplementedSDSControllerServer) DeletePool(context.Context, *DeletePoolRequest) (*DeletePoolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePool not implemented")
}
func (UnimplementedSDSControllerServer) GetPool(context.Context, *GetPoolRequest) (*GetPoolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPool not implemented")
}
func (UnimplementedSDSControllerServer) ListPools(context.Context, *ListPoolsRequest) (*ListPoolsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPools not implemented")
}
func (UnimplementedSDSControllerServer) AddDiskToPool(context.Context, *AddDiskToPoolRequest) (*AddDiskToPoolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddDiskToPool not implemented")
}
func (UnimplementedSDSControllerServer) RegisterNode(context.Context, *RegisterNodeRequest) (*RegisterNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterNode not implemented")
}
func (UnimplementedSDSControllerServer) UnregisterNode(context.Context, *UnregisterNodeRequest) (*UnregisterNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnregisterNode not implemented")
}
func (UnimplementedSDSControllerServer) GetNode(context.Context, *GetNodeRequest) (*GetNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNode not implemented")
}
func (UnimplementedSDSControllerServer) ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNodes not implemented")
}
func (UnimplementedSDSControllerServer) CreateResource(context.Context, *CreateResourceRequest) (*CreateResourceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateResource not implemented")
}
func (UnimplementedSDSControllerServer) DeleteResource(context.Context, *DeleteResourceRequest) (*DeleteResourceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteResource not implemented")
}
func (UnimplementedSDSControllerServer) GetResource(context.Context, *GetResourceRequest) (*GetResourceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetResource not implemented")
}
func (UnimplementedSDSControllerServer) ListResources(context.Context, *ListResourcesRequest) (*ListResourcesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListResources not implemented")
}
func (UnimplementedSDSControllerServer) AddVolume(context.Context, *AddVolumeRequest) (*AddVolumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddVolume not implemented")
}
func (UnimplementedSDSControllerServer) RemoveVolume(context.Context, *RemoveVolumeRequest) (*RemoveVolumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveVolume not implemented")
}
func (UnimplementedSDSControllerServer) ResizeVolume(context.Context, *ResizeVolumeRequest) (*ResizeVolumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResizeVolume not implemented")
}
func (UnimplementedSDSControllerServer) ResourceStatus(context.Context, *ResourceStatusRequest) (*ResourceStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResourceStatus not implemented")
}
func (UnimplementedSDSControllerServer) SetPrimary(context.Context, *SetPrimaryRequest) (*SetPrimaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetPrimary not implemented")
}
func (UnimplementedSDSControllerServer) SetSecondary(context.Context, *SetSecondaryRequest) (*SetSecondaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetSecondary not implemented")
}
func (UnimplementedSDSControllerServer) CreateFilesystem(context.Context, *CreateFilesystemRequest) (*CreateFilesystemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateFilesystem not implemented")
}
func (UnimplementedSDSControllerServer) MountResource(context.Context, *MountResourceRequest) (*MountResourceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MountResource not implemented")
}
func (UnimplementedSDSControllerServer) UnmountResource(context.Context, *UnmountResourceRequest) (*UnmountResourceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnmountResource not implemented")
}
func (UnimplementedSDSControllerServer) MakeHa(context.Context, *MakeHaRequest) (*MakeHaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MakeHa not implemented")
}
func (UnimplementedSDSControllerServer) EvictHa(context.Context, *EvictHaRequest) (*EvictHaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EvictHa not implemented")
}
func (UnimplementedSDSControllerServer) DeleteHa(context.Context, *DeleteHaRequest) (*DeleteHaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteHa not implemented")
}
func (UnimplementedSDSControllerServer) GetHa(context.Context, *GetHaRequest) (*GetHaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHa not implemented")
}
func (UnimplementedSDSControllerServer) ListHa(context.Context, *ListHaRequest) (*ListHaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListHa not implemented")
}
func (UnimplementedSDSControllerServer) CreateSnapshot(context.Context, *CreateSnapshotRequest) (*CreateSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSnapshot not implemented")
}
func (UnimplementedSDSControllerServer) DeleteSnapshot(context.Context, *DeleteSnapshotRequest) (*DeleteSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSnapshot not implemented")
}
func (UnimplementedSDSControllerServer) RestoreSnapshot(context.Context, *RestoreSnapshotRequest) (*RestoreSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RestoreSnapshot not implemented")
}
func (UnimplementedSDSControllerServer) ListSnapshots(context.Context, *ListSnapshotsRequest) (*ListSnapshotsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSnapshots not implemented")
}
func (UnimplementedSDSControllerServer) CreateNFSGateway(context.Context, *CreateNFSGatewayRequest) (*CreateNFSGatewayResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateNFSGateway not implemented")
}
func (UnimplementedSDSControllerServer) CreateISCSIGateway(context.Context, *CreateISCSIGatewayRequest) (*CreateISCSIGatewayResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateISCSIGateway not implemented")
}
func (UnimplementedSDSControllerServer) CreateNVMeGateway(context.Context, *CreateNVMeGatewayRequest) (*CreateNVMeGatewayResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateNVMeGateway not implemented")
}
func (UnimplementedSDSControllerServer) DeleteGateway(context.Context, *DeleteGatewayRequest) (*DeleteGatewayResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteGateway not implemented")
}
func (UnimplementedSDSControllerServer) GetGateway(context.Context, *GetGatewayRequest) (*GetGatewayResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGateway not implemented")
}
func (UnimplementedSDSControllerServer) ListGateways(context.Context, *ListGatewaysRequest) (*ListGatewaysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListGateways not implemented")
}
func (UnimplementedSDSControllerServer) StartGateway(context.Context, *StartGatewayRequest) (*StartGatewayResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartGateway not implemented")
}
func (UnimplementedSDSControllerServer) StopGateway(context.Context, *StopGatewayRequest) (*StopGatewayResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopGateway not implemented")
}
func (UnimplementedSDSControllerServer) CreateZFSPool(context.Context, *CreateZFSPoolRequest) (*CreateZFSPoolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateZFSPool not implemented")
}
func (UnimplementedSDSControllerServer) DeleteZFSPool(context.Context, *DeleteZFSPoolRequest) (*DeleteZFSPoolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteZFSPool not implemented")
}
func (UnimplementedSDSControllerServer) ListZFSpools(context.Context, *ListZFSPoolsRequest) (*ListZFSPoolsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListZFSpools not implemented")
}
func (UnimplementedSDSControllerServer) CreateZFSDataset(context.Context, *CreateZFSDatasetRequest) (*CreateZFSDatasetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateZFSDataset not implemented")
}
func (UnimplementedSDSControllerServer) CreateZFSVolume(context.Context, *CreateZFSVolumeRequest) (*CreateZFSVolumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateZFSVolume not implemented")
}
func (UnimplementedSDSControllerServer) ResizeZFSVolume(context.Context, *ResizeZFSVolumeRequest) (*ResizeZFSVolumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResizeZFSVolume not implemented")
}
func (UnimplementedSDSControllerServer) DeleteZFSDataset(context.Context, *DeleteZFSDatasetRequest) (*DeleteZFSDatasetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteZFSDataset not implemented")
}
func (UnimplementedSDSControllerServer) CreateZFSSnapshot(context.Context, *CreateZFSSnapshotRequest) (*CreateZFSSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateZFSSnapshot not implemented")
}
func (UnimplementedSDSControllerServer) DeleteZFSSnapshot(context.Context, *DeleteZFSSnapshotRequest) (*DeleteZFSSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteZFSSnapshot not implemented")
}
func (UnimplementedSDSControllerServer) ListZFSSnapshots(context.Context, *ListZFSSnapshotsRequest) (*ListZFSSnapshotsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListZFSSnapshots not implemented")
}
func (UnimplementedSDSControllerServer) RestoreZFSSnapshot(context.Context, *RestoreZFSSnapshotRequest) (*RestoreZFSSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RestoreZFSSnapshot not implemented")
}
func (UnimplementedSDSControllerServer) CloneZFSSnapshot(context.Context, *CloneZFSSnapshotRequest) (*CloneZFSSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CloneZFSSnapshot not implemented")
}
func (UnimplementedSDSControllerServer) CreateLvmSnapshot(context.Context, *CreateLvmSnapshotRequest) (*CreateLvmSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateLvmSnapshot not implemented")
}
func (UnimplementedSDSControllerServer) DeleteLvmSnapshot(context.Context, *DeleteLvmSnapshotRequest) (*DeleteLvmSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteLvmSnapshot not implemented")
}
func (UnimplementedSDSControllerServer) ListLvmSnapshots(context.Context, *ListLvmSnapshotsRequest) (*ListLvmSnapshotsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLvmSnapshots not implemented")
}
func (UnimplementedSDSControllerServer) RestoreLvmSnapshot(context.Context, *RestoreLvmSnapshotRequest) (*RestoreLvmSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RestoreLvmSnapshot not implemented")
}
func (UnimplementedSDSControllerServer) mustEmbedUnimplementedSDSControllerServer() {}
func (UnimplementedSDSControllerServer) testEmbeddedByValue()                       {}

// UnsafeSDSControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SDSControllerServer will
// result in compilation errors.
type UnsafeSDSControllerServer interface {
	mustEmbedUnimplementedSDSControllerServer()
}

func RegisterSDSControllerServer(s grpc.ServiceRegistrar, srv SDSControllerServer) {
	// If the following call panics, it indicates UnimplementedSDSControllerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SDSController_ServiceDesc, srv)
}

func _SDSController_CreatePool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDSControllerServer).CreatePool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDSController_CreatePool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDSControllerServer).CreatePool(ctx, req.(*CreatePoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDSController_DeletePool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDSControllerServer).DeletePool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDSController_DeletePool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDSControllerServer).DeletePool(ctx, req.(*DeletePoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDSController_GetPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDSControllerServer).GetPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDSController_GetPool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDSControllerServer).GetPool(ctx, req.(*GetPoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDSController_ListPools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPoolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDSControllerServer).ListPools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDSController_ListPools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDSControllerServer).ListPools(ctx, req.(*ListPoolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDSController_AddDiskToPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddDiskToPoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDSControllerServer).AddDiskToPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDSController_AddDiskToPool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDSControllerServer).AddDiskToPool(ctx, req.(*AddDiskToPoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDSController_RegisterNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDSControllerServer).RegisterNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDSController_RegisterNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDSControllerServer).RegisterNode(ctx, req.(*RegisterNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDSController_UnregisterNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDSControllerServer).UnregisterNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDSController_UnregisterNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDSControllerServer).UnregisterNode(ctx, req.(*UnregisterNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDSController_GetNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDSControllerServer).GetNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDSController_GetNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDSControllerServer).GetNode(ctx, req.(*GetNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDSController_ListNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDSControllerServer).ListNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDSController_ListNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDSControllerServer).ListNodes(ctx, req.(*ListNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDSController_CreateResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDSControllerServer).CreateResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDSController_CreateResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDSControllerServer).CreateResource(ctx, req.(*CreateResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDSController_DeleteResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDSControllerServer).DeleteResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDSController_DeleteResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDSControllerServer).DeleteResource(ctx, req.(*DeleteResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDSController_GetResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDSControllerServer).GetResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDSController_GetResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDSControllerServer).GetResource(ctx, req.(*GetResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDSController_ListResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListResourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDSControllerServer).ListResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDSController_ListResources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDSControllerServer).ListResources(ctx, req.(*ListResourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDSController_AddVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDSControllerServer).AddVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDSController_AddVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDSControllerServer).AddVolume(ctx, req.(*AddVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDSController_RemoveVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDSControllerServer).RemoveVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDSController_RemoveVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDSControllerServer).RemoveVolume(ctx, req.(*RemoveVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDSController_ResizeVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResizeVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDSControllerServer).ResizeVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDSController_ResizeVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDSControllerServer).ResizeVolume(ctx, req.(*ResizeVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDSController_ResourceStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourceStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDSControllerServer).ResourceStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDSController_ResourceStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDSControllerServer).ResourceStatus(ctx, req.(*ResourceStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDSController_SetPrimary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPrimaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDSControllerServer).SetPrimary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDSController_SetPrimary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDSControllerServer).SetPrimary(ctx, req.(*SetPrimaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDSController_SetSecondary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSecondaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDSControllerServer).SetSecondary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDSController_SetSecondary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDSControllerServer).SetSecondary(ctx, req.(*SetSecondaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDSController_CreateFilesystem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFilesystemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDSControllerServer).CreateFilesystem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDSController_CreateFilesystem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDSControllerServer).CreateFilesystem(ctx, req.(*CreateFilesystemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDSController_MountResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MountResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDSControllerServer).MountResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDSController_MountResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDSControllerServer).MountResource(ctx, req.(*MountResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDSController_UnmountResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnmountResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDSControllerServer).UnmountResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDSController_UnmountResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDSControllerServer).UnmountResource(ctx, req.(*UnmountResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDSController_MakeHa_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MakeHaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDSControllerServer).MakeHa(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDSController_MakeHa_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDSControllerServer).MakeHa(ctx, req.(*MakeHaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDSController_EvictHa_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvictHaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDSControllerServer).EvictHa(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDSController_EvictHa_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDSControllerServer).EvictHa(ctx, req.(*EvictHaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDSController_DeleteHa_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteHaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDSControllerServer).DeleteHa(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDSController_DeleteHa_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDSControllerServer).DeleteHa(ctx, req.(*DeleteHaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDSController_GetHa_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDSControllerServer).GetHa(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDSController_GetHa_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDSControllerServer).GetHa(ctx, req.(*GetHaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDSController_ListHa_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDSControllerServer).ListHa(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDSController_ListHa_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDSControllerServer).ListHa(ctx, req.(*ListHaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDSController_CreateSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDSControllerServer).CreateSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDSController_CreateSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDSControllerServer).CreateSnapshot(ctx, req.(*CreateSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDSController_DeleteSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDSControllerServer).DeleteSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDSController_DeleteSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDSControllerServer).DeleteSnapshot(ctx, req.(*DeleteSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDSController_RestoreSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDSControllerServer).RestoreSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDSController_RestoreSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDSControllerServer).RestoreSnapshot(ctx, req.(*RestoreSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDSController_ListSnapshots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSnapshotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDSControllerServer).ListSnapshots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDSController_ListSnapshots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDSControllerServer).ListSnapshots(ctx, req.(*ListSnapshotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDSController_CreateNFSGateway_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNFSGatewayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDSControllerServer).CreateNFSGateway(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDSController_CreateNFSGateway_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDSControllerServer).CreateNFSGateway(ctx, req.(*CreateNFSGatewayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDSController_CreateISCSIGateway_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateISCSIGatewayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDSControllerServer).CreateISCSIGateway(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDSController_CreateISCSIGateway_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDSControllerServer).CreateISCSIGateway(ctx, req.(*CreateISCSIGatewayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDSController_CreateNVMeGateway_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNVMeGatewayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDSControllerServer).CreateNVMeGateway(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDSController_CreateNVMeGateway_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDSControllerServer).CreateNVMeGateway(ctx, req.(*CreateNVMeGatewayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDSController_DeleteGateway_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGatewayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDSControllerServer).DeleteGateway(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDSController_DeleteGateway_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDSControllerServer).DeleteGateway(ctx, req.(*DeleteGatewayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDSController_GetGateway_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGatewayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDSControllerServer).GetGateway(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDSController_GetGateway_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDSControllerServer).GetGateway(ctx, req.(*GetGatewayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDSController_ListGateways_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGatewaysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDSControllerServer).ListGateways(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDSController_ListGateways_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDSControllerServer).ListGateways(ctx, req.(*ListGatewaysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDSController_StartGateway_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartGatewayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDSControllerServer).StartGateway(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDSController_StartGateway_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDSControllerServer).StartGateway(ctx, req.(*StartGatewayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDSController_StopGateway_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopGatewayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDSControllerServer).StopGateway(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDSController_StopGateway_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDSControllerServer).StopGateway(ctx, req.(*StopGatewayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDSController_CreateZFSPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateZFSPoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDSControllerServer).CreateZFSPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDSController_CreateZFSPool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDSControllerServer).CreateZFSPool(ctx, req.(*CreateZFSPoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDSController_DeleteZFSPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteZFSPoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDSControllerServer).DeleteZFSPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDSController_DeleteZFSPool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDSControllerServer).DeleteZFSPool(ctx, req.(*DeleteZFSPoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDSController_ListZFSpools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListZFSPoolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDSControllerServer).ListZFSpools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDSController_ListZFSpools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDSControllerServer).ListZFSpools(ctx, req.(*ListZFSPoolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDSController_CreateZFSDataset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateZFSDatasetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDSControllerServer).CreateZFSDataset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDSController_CreateZFSDataset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDSControllerServer).CreateZFSDataset(ctx, req.(*CreateZFSDatasetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDSController_CreateZFSVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateZFSVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDSControllerServer).CreateZFSVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDSController_CreateZFSVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDSControllerServer).CreateZFSVolume(ctx, req.(*CreateZFSVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDSController_ResizeZFSVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResizeZFSVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDSControllerServer).ResizeZFSVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDSController_ResizeZFSVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDSControllerServer).ResizeZFSVolume(ctx, req.(*ResizeZFSVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDSController_DeleteZFSDataset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteZFSDatasetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDSControllerServer).DeleteZFSDataset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDSController_DeleteZFSDataset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDSControllerServer).DeleteZFSDataset(ctx, req.(*DeleteZFSDatasetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDSController_CreateZFSSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateZFSSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDSControllerServer).CreateZFSSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDSController_CreateZFSSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDSControllerServer).CreateZFSSnapshot(ctx, req.(*CreateZFSSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDSController_DeleteZFSSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteZFSSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDSControllerServer).DeleteZFSSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDSController_DeleteZFSSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDSControllerServer).DeleteZFSSnapshot(ctx, req.(*DeleteZFSSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDSController_ListZFSSnapshots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListZFSSnapshotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDSControllerServer).ListZFSSnapshots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDSController_ListZFSSnapshots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDSControllerServer).ListZFSSnapshots(ctx, req.(*ListZFSSnapshotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDSController_RestoreZFSSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreZFSSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDSControllerServer).RestoreZFSSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDSController_RestoreZFSSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDSControllerServer).RestoreZFSSnapshot(ctx, req.(*RestoreZFSSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDSController_CloneZFSSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloneZFSSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDSControllerServer).CloneZFSSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDSController_CloneZFSSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDSControllerServer).CloneZFSSnapshot(ctx, req.(*CloneZFSSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDSController_CreateLvmSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLvmSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDSControllerServer).CreateLvmSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDSController_CreateLvmSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDSControllerServer).CreateLvmSnapshot(ctx, req.(*CreateLvmSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDSController_DeleteLvmSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLvmSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDSControllerServer).DeleteLvmSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDSController_DeleteLvmSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDSControllerServer).DeleteLvmSnapshot(ctx, req.(*DeleteLvmSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDSController_ListLvmSnapshots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLvmSnapshotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDSControllerServer).ListLvmSnapshots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDSController_ListLvmSnapshots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDSControllerServer).ListLvmSnapshots(ctx, req.(*ListLvmSnapshotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SDSController_RestoreLvmSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreLvmSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SDSControllerServer).RestoreLvmSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SDSController_RestoreLvmSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SDSControllerServer).RestoreLvmSnapshot(ctx, req.(*RestoreLvmSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SDSController_ServiceDesc is the grpc.ServiceDesc for SDSController service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SDSController_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.SDSController",
	HandlerType: (*SDSControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePool",
			Handler:    _SDSController_CreatePool_Handler,
		},
		{
			MethodName: "DeletePool",
			Handler:    _SDSController_DeletePool_Handler,
		},
		{
			MethodName: "GetPool",
			Handler:    _SDSController_GetPool_Handler,
		},
		{
			MethodName: "ListPools",
			Handler:    _SDSController_ListPools_Handler,
		},
		{
			MethodName: "AddDiskToPool",
			Handler:    _SDSController_AddDiskToPool_Handler,
		},
		{
			MethodName: "RegisterNode",
			Handler:    _SDSController_RegisterNode_Handler,
		},
		{
			MethodName: "UnregisterNode",
			Handler:    _SDSController_UnregisterNode_Handler,
		},
		{
			MethodName: "GetNode",
			Handler:    _SDSController_GetNode_Handler,
		},
		{
			MethodName: "ListNodes",
			Handler:    _SDSController_ListNodes_Handler,
		},
		{
			MethodName: "CreateResource",
			Handler:    _SDSController_CreateResource_Handler,
		},
		{
			MethodName: "DeleteResource",
			Handler:    _SDSController_DeleteResource_Handler,
		},
		{
			MethodName: "GetResource",
			Handler:    _SDSController_GetResource_Handler,
		},
		{
			MethodName: "ListResources",
			Handler:    _SDSController_ListResources_Handler,
		},
		{
			MethodName: "AddVolume",
			Handler:    _SDSController_AddVolume_Handler,
		},
		{
			MethodName: "RemoveVolume",
			Handler:    _SDSController_RemoveVolume_Handler,
		},
		{
			MethodName: "ResizeVolume",
			Handler:    _SDSController_ResizeVolume_Handler,
		},
		{
			MethodName: "ResourceStatus",
			Handler:    _SDSController_ResourceStatus_Handler,
		},
		{
			MethodName: "SetPrimary",
			Handler:    _SDSController_SetPrimary_Handler,
		},
		{
			MethodName: "SetSecondary",
			Handler:    _SDSController_SetSecondary_Handler,
		},
		{
			MethodName: "CreateFilesystem",
			Handler:    _SDSController_CreateFilesystem_Handler,
		},
		{
			MethodName: "MountResource",
			Handler:    _SDSController_MountResource_Handler,
		},
		{
			MethodName: "UnmountResource",
			Handler:    _SDSController_UnmountResource_Handler,
		},
		{
			MethodName: "MakeHa",
			Handler:    _SDSController_MakeHa_Handler,
		},
		{
			MethodName: "EvictHa",
			Handler:    _SDSController_EvictHa_Handler,
		},
		{
			MethodName: "DeleteHa",
			Handler:    _SDSController_DeleteHa_Handler,
		},
		{
			MethodName: "GetHa",
			Handler:    _SDSController_GetHa_Handler,
		},
		{
			MethodName: "ListHa",
			Handler:    _SDSController_ListHa_Handler,
		},
		{
			MethodName: "CreateSnapshot",
			Handler:    _SDSController_CreateSnapshot_Handler,
		},
		{
			MethodName: "DeleteSnapshot",
			Handler:    _SDSController_DeleteSnapshot_Handler,
		},
		{
			MethodName: "RestoreSnapshot",
			Handler:    _SDSController_RestoreSnapshot_Handler,
		},
		{
			MethodName: "ListSnapshots",
			Handler:    _SDSController_ListSnapshots_Handler,
		},
		{
			MethodName: "CreateNFSGateway",
			Handler:    _SDSController_CreateNFSGateway_Handler,
		},
		{
			MethodName: "CreateISCSIGateway",
			Handler:    _SDSController_CreateISCSIGateway_Handler,
		},
		{
			MethodName: "CreateNVMeGateway",
			Handler:    _SDSController_CreateNVMeGateway_Handler,
		},
		{
			MethodName: "DeleteGateway",
			Handler:    _SDSController_DeleteGateway_Handler,
		},
		{
			MethodName: "GetGateway",
			Handler:    _SDSController_GetGateway_Handler,
		},
		{
			MethodName: "ListGateways",
			Handler:    _SDSController_ListGateways_Handler,
		},
		{
			MethodName: "StartGateway",
			Handler:    _SDSController_StartGateway_Handler,
		},
		{
			MethodName: "StopGateway",
			Handler:    _SDSController_StopGateway_Handler,
		},
		{
			MethodName: "CreateZFSPool",
			Handler:    _SDSController_CreateZFSPool_Handler,
		},
		{
			MethodName: "DeleteZFSPool",
			Handler:    _SDSController_DeleteZFSPool_Handler,
		},
		{
			MethodName: "ListZFSpools",
			Handler:    _SDSController_ListZFSpools_Handler,
		},
		{
			MethodName: "CreateZFSDataset",
			Handler:    _SDSController_CreateZFSDataset_Handler,
		},
		{
			MethodName: "CreateZFSVolume",
			Handler:    _SDSController_CreateZFSVolume_Handler,
		},
		{
			MethodName: "ResizeZFSVolume",
			Handler:    _SDSController_ResizeZFSVolume_Handler,
		},
		{
			MethodName: "DeleteZFSDataset",
			Handler:    _SDSController_DeleteZFSDataset_Handler,
		},
		{
			MethodName: "CreateZFSSnapshot",
			Handler:    _SDSController_CreateZFSSnapshot_Handler,
		},
		{
			MethodName: "DeleteZFSSnapshot",
			Handler:    _SDSController_DeleteZFSSnapshot_Handler,
		},
		{
			MethodName: "ListZFSSnapshots",
			Handler:    _SDSController_ListZFSSnapshots_Handler,
		},
		{
			MethodName: "RestoreZFSSnapshot",
			Handler:    _SDSController_RestoreZFSSnapshot_Handler,
		},
		{
			MethodName: "CloneZFSSnapshot",
			Handler:    _SDSController_CloneZFSSnapshot_Handler,
		},
		{
			MethodName: "CreateLvmSnapshot",
			Handler:    _SDSController_CreateLvmSnapshot_Handler,
		},
		{
			MethodName: "DeleteLvmSnapshot",
			Handler:    _SDSController_DeleteLvmSnapshot_Handler,
		},
		{
			MethodName: "ListLvmSnapshots",
			Handler:    _SDSController_ListLvmSnapshots_Handler,
		},
		{
			MethodName: "RestoreLvmSnapshot",
			Handler:    _SDSController_RestoreLvmSnapshot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/v1/sds.proto",
}
