package controller

import (
	"fmt"
	"strings"
)

// selfHaSSHOpts are the options for every script-driven SSH hop. accept-new
// matters: after a failover the script may run on a node whose root user has
// never connected to its peers, so known_hosts entries cannot be assumed.
const selfHaSSHOpts = "-o BatchMode=yes -o StrictHostKeyChecking=accept-new -o ConnectTimeout=10"

// generateSelfHaHandoffScript renders the node-local handoff script that
// finishes the self-HA enablement after the controller stops itself:
//
//  1. stop + disable the standalone controller
//  2. copy the database onto the (still locally Primary) DRBD volume
//  3. activate the reactor config locally first — reactor immediately
//     promotes this node (it already holds Primary), mounts the database,
//     brings the VIP up, and starts the controller
//  4. activate the reactor config on the standbys — they see a peer Primary
//     and stay passive
//
// The script is executed by systemd-run in its own transient unit, so it
// survives `systemctl stop haify-controller`. On any failure it rolls back to
// a standalone controller.
func generateSelfHaHandoffScript(standbyAddrs []string) string {
	var sb strings.Builder
	sb.WriteString(`#!/bin/bash
# Generated by haify-controller: self-HA handoff. Do not edit.
mkdir -p /var/log/haify
exec >> ` + selfHaHandoffLog + ` 2>&1
echo "[selfha] handoff started: $(date -Is)"
set -x

REACTOR_CONF=` + selfHaReactorConfig + `
TMP_MNT=/mnt/haify-meta-handoff
DB_DIR=` + selfHaMountPoint + `

rollback() {
    echo "[selfha] handoff FAILED, rolling back to standalone controller"
    umount "$TMP_MNT" 2>/dev/null
    rm -f "$REACTOR_CONF"
    systemctl reload drbd-reactor 2>/dev/null
`)
	for _, addr := range standbyAddrs {
		fmt.Fprintf(&sb,
			"    ssh %s %s 'sudo rm -f %s && sudo systemctl reload drbd-reactor' 2>/dev/null\n",
			selfHaSSHOpts, addr, selfHaReactorConfig)
	}
	sb.WriteString(`    systemctl enable --now haify-controller
    echo "[selfha] rollback finished: $(date -Is)"
    exit 1
}
trap rollback ERR
set -e

# 1. Stop the standalone controller; reactor owns it from now on.
systemctl stop haify-controller
systemctl disable haify-controller 2>/dev/null || true

# 2. Copy the database onto the DRBD volume (this node holds Primary).
mkdir -p "$TMP_MNT"
mount /dev/drbd/by-res/` + SelfHaResource + `/0 "$TMP_MNT"
cp -a "$DB_DIR/haify.db" "$TMP_MNT/haify.db"
sync
umount "$TMP_MNT"

# 3. Activate reactor management locally first: reactor promotes this node
# (already Primary), mounts the database, starts the VIP and the controller.
mv "$REACTOR_CONF.disabled" "$REACTOR_CONF"
systemctl reload drbd-reactor
`)
	if len(standbyAddrs) > 0 {
		sb.WriteString("\n# 4. Activate on standbys: they see a peer Primary and stay passive.\n")
		for _, addr := range standbyAddrs {
			fmt.Fprintf(&sb,
				"ssh %s %s 'sudo mv %s.disabled %s && sudo systemctl reload drbd-reactor'\n",
				selfHaSSHOpts, addr, selfHaReactorConfig, selfHaReactorConfig)
		}
	}
	sb.WriteString(`
# 5. Verify the controller came back under reactor management.
for i in $(seq 1 30); do
    if systemctl is-active --quiet haify-controller; then
        break
    fi
    sleep 2
done
systemctl is-active --quiet haify-controller
echo "[selfha] handoff complete: $(date -Is)"
`)
	return sb.String()
}

// selfHaReactorDropins lists the transient systemd drop-in directories
// drbd-reactor generates for the units it manages. They survive plugin
// config removal, and a leftover haify-controller drop-in would drag the DRBD
// promote/mount/VIP dependencies back in when the standalone controller
// starts — so disable must remove them explicitly. vip may be empty (e.g. on
// a disable retry where the HA config record is already gone); the VIP
// drop-in is then skipped, which is benign.
func selfHaReactorDropins(vip string) string {
	escaped := strings.ReplaceAll(SelfHaResource, "-", `\x2d`)
	dropins := fmt.Sprintf(
		`/run/systemd/system/haify-controller.service.d `+
			`/run/systemd/system/var-lib-haify.mount.d `+
			`"/run/systemd/system/drbd-promote@%s.service.d" `+
			`"/run/systemd/system/drbd-demote-or-escalate@%s.service.d" `+
			`"/run/systemd/system/drbd-services@%s.target.d"`,
		escaped, escaped, escaped)
	if inst := vipServiceIPInstance(vip); inst != "" {
		dropins += fmt.Sprintf(` "/run/systemd/system/service-ip@%s.service.d"`, inst)
	}
	return dropins
}

// generateSelfHaDisableScript renders the node-local script reverting the
// controller to standalone operation on targetAddr. It runs on the currently
// active controller node (selfAddr); remote steps go over SSH.
//
// Ordering is failure-aware: reactor configs are removed on the OTHER nodes
// first — losing a passive node's config is benign, the active node keeps
// serving. Only then is local management torn down. The reactor target is
// stopped explicitly because removing a plugin config does not reliably stop
// units it already started, and the reactor-generated drop-ins are removed
// so the standalone controller does not re-trigger promote/mount/VIP via
// stale dependencies. On failure the trap restores local reactor management
// from a backup of the config.
func generateSelfHaDisableScript(otherAddrs []string, targetAddr, selfAddr, vip string) string {
	dropins := selfHaReactorDropins(vip)

	// The VIP's service-ip@ unit is Type=oneshot RemainAfterExit=yes, so
	// stopping the drbd-services target and removing its drop-in does not
	// bring the floating IP down on its own — it must be stopped explicitly or
	// it lingers on the node that was active. Idempotent: stopping an
	// inactive/absent template instance is a no-op. vipInst is "" on a disable
	// retry where the HA config record (and thus the VIP) is already gone,
	// which is benign.
	vipInst := vipServiceIPInstance(vip)
	vipStopRemote, vipStopLocal := "", ""
	if vipInst != "" {
		vipStopRemote = fmt.Sprintf("sudo systemctl stop service-ip@%s.service 2>/dev/null; ", vipInst)
		vipStopLocal = fmt.Sprintf("systemctl stop service-ip@%s.service 2>/dev/null || true\n", vipInst)
	}

	var sb strings.Builder
	sb.WriteString(`#!/bin/bash
# Generated by haify-controller: self-HA disable. Do not edit.
mkdir -p /var/log/haify
exec >> ` + selfHaDisableLog + ` 2>&1
echo "[selfha] disable started: $(date -Is)"
set -x

REACTOR_CONF=` + selfHaReactorConfig + `
TMP_MNT=/mnt/haify-meta-handoff
DB_DIR=` + selfHaMountPoint + `
TARGET_UNIT="drbd-services@$(systemd-escape "` + SelfHaResource + `").target"
CONF_BACKUP=/tmp/haify-ha-` + SelfHaResource + `.toml.bak

rollback() {
    echo "[selfha] disable FAILED, restoring reactor management on this node"
    umount "$TMP_MNT" 2>/dev/null
    if [ -f "$CONF_BACKUP" ]; then
        cp -a "$CONF_BACKUP" "$REACTOR_CONF"
        systemctl reload drbd-reactor 2>/dev/null
        systemctl start "$TARGET_UNIT" 2>/dev/null
    fi
    echo "[selfha] rollback finished: $(date -Is); rerun 'ha self disable' after fixing the cause"
    exit 1
}
trap rollback ERR
set -e

cp -a "$REACTOR_CONF" "$CONF_BACKUP" 2>/dev/null || true

# 1. Remove reactor management on the passive nodes first: harmless if a
# step fails, the active controller keeps running. Reactor-generated
# drop-ins and the mount unit are removed too, so nothing re-triggers
# promote/mount/VIP through stale systemd dependencies.
`)
	for _, addr := range otherAddrs {
		fmt.Fprintf(&sb,
			"ssh %s %s 'sudo rm -f %s %s.disabled && sudo systemctl stop \"drbd-services@$(systemd-escape \"%s\").target\" 2>/dev/null; %ssudo systemctl reload drbd-reactor; sudo rm -rf %s; sudo rm -f /etc/systemd/system/var-lib-haify.mount; sudo systemctl daemon-reload'\n",
			selfHaSSHOpts, addr, selfHaReactorConfig, selfHaReactorConfig, SelfHaResource, vipStopRemote, dropins)
	}

	sb.WriteString(`
# 2. Tear down local reactor management. Stopping the target explicitly is
# required: drbd-reactor does not reliably stop units after its plugin
# config disappears. This stops the managed controller, the VIP, and the
# database mount, and demotes the DRBD resource.
rm -f "$REACTOR_CONF" "$REACTOR_CONF.disabled"
systemctl reload drbd-reactor
systemctl stop "$TARGET_UNIT" 2>/dev/null || true
` + vipStopLocal + `rm -rf ` + dropins + `
rm -f /etc/systemd/system/var-lib-haify.mount
systemctl daemon-reload
sleep 3

# 3. Restore the database onto the target node and start the controller.
restore_cmds='set -ex
sudo drbdadm primary ` + SelfHaResource + `
sudo mkdir -p '"$TMP_MNT"'
sudo mount /dev/drbd/by-res/` + SelfHaResource + `/0 '"$TMP_MNT"'
sudo mkdir -p '"$DB_DIR"'
sudo cp -a '"$TMP_MNT"'/haify.db '"$DB_DIR"'/haify.db
sync
sudo umount '"$TMP_MNT"'
sudo drbdadm secondary ` + SelfHaResource + `
sudo systemctl enable --now haify-controller'
`)
	if targetAddr == selfAddr {
		sb.WriteString(`
bash -c "${restore_cmds//sudo /}"
`)
	} else {
		fmt.Fprintf(&sb, `
ssh %s %s "$restore_cmds"
`, selfHaSSHOpts, targetAddr)
	}
	sb.WriteString(`rm -f "$CONF_BACKUP"
echo "[selfha] disable complete: $(date -Is)"
`)
	return sb.String()
}
